// _db.js — Expanded seed data covering all Indian political levels
// Panchayat → Block → District → State → National

export const newsCache = new Map([
  [
    "1",
    [
      { title: "Minister Rajesh Kumar inaugurates 200km highway stretch in Rajasthan", url: "https://timesofindia.com/india/rajesh-kumar-highway", source: "Times of India", publishedAt: "Fri, 18 Apr 2025 08:00:00 +0530" },
      { title: "Highway project cost overrun triggers CAG audit in Rajasthan", url: "https://thehindu.com/news/highway-cag", source: "The Hindu", publishedAt: "Mon, 14 Apr 2025 10:30:00 +0530" },
      { title: "Opposition demands probe into NH-48 contract award irregularities", url: "https://ndtv.com/india/nh48-probe", source: "NDTV", publishedAt: "Wed, 09 Apr 2025 15:00:00 +0530" },
    ],
  ],
  [
    "2",
    [
      { title: "MP Priya Deshmukh tables amendment for NEP rural inclusion in Lok Sabha", url: "https://indianexpress.com/priya-deshmukh-nep", source: "Indian Express", publishedAt: "Tue, 15 Apr 2025 09:00:00 +0530" },
      { title: "Promised rural schools in Maharashtra: 2 years, zero construction", url: "https://scroll.in/maharashtra-schools", source: "Scroll.in", publishedAt: "Thu, 03 Apr 2025 11:00:00 +0530" },
    ],
  ],
  [
    "3",
    [
      { title: "Lucknow DC Vikram Singh launches monsoon drainage audit drive", url: "https://hindustantimes.com/lucknow-drainage", source: "Hindustan Times", publishedAt: "Sat, 12 Apr 2025 07:30:00 +0530" },
      { title: "Whistleblower alleges ghost workers in Lucknow sewage project", url: "https://thewire.in/lucknow-ghost-workers", source: "The Wire", publishedAt: "Mon, 07 Apr 2025 14:00:00 +0530" },
    ],
  ],
  [
    "4",
    [
      { title: "Home Minister Arjun Mehta unveils National Policing Framework 2025", url: "https://pib.gov.in/arjun-mehta-npi", source: "Press Information Bureau", publishedAt: "Thu, 17 Apr 2025 06:00:00 +0530" },
      { title: "CBI registers preliminary enquiry into UPCOCA misuse allegations against minister", url: "https://livelaw.in/arjun-mehta-cbi", source: "Live Law", publishedAt: "Tue, 08 Apr 2025 12:00:00 +0530" },
    ],
  ],
  [
    "5",
    [
      { title: "Rajya Sabha MP Kavitha Reddy raises BRS demand for special status to Telangana", url: "https://deccanchronicle.com/kavitha-reddy-rajya-sabha", source: "Deccan Chronicle", publishedAt: "Wed, 16 Apr 2025 10:00:00 +0530" },
      { title: "Telangana MP faces ED summons in Hyderabad land scam case", url: "https://thehindu.com/kavitha-reddy-ed", source: "The Hindu", publishedAt: "Fri, 04 Apr 2025 09:30:00 +0530" },
    ],
  ],
  [
    "6",
    [
      { title: "Kerala CM Suresh Nair inaugurates state's largest solar power plant", url: "https://mathrubhumi.com/suresh-nair-solar", source: "Mathrubhumi", publishedAt: "Sun, 13 Apr 2025 08:00:00 +0530" },
      { title: "Kerala CM faces heat over KIIFB borrowing transparency", url: "https://kerala.indianexpress.com/kiifb-row", source: "Indian Express Kerala", publishedAt: "Mon, 05 Apr 2025 11:00:00 +0530" },
    ],
  ],
  [
    "7",
    [
      { title: "TMC MLA Fatima Ahmed inaugurates 1000-seat women's shelter in Kolkata", url: "https://telegraphindia.com/fatima-ahmed-shelter", source: "The Telegraph", publishedAt: "Sat, 10 Apr 2025 09:00:00 +0530" },
    ],
  ],
]);

let officials = [
  // ===================== NATIONAL LEVEL =====================
  {
    id: "1",
    name: "Rajesh Kumar Sharma",
    role: "POLITICIAN",
    level: "NATIONAL",
    party: "Bharatiya Janata Party",
    department: "Ministry of Road Transport and Highways",
    position: "Minister of State",
    constituency: "Jaipur Rural",
    constituencyType: "Lok Sabha",
    state: "Rajasthan",
    district: "Jaipur",
    assets: 45000000,
    criminalCases: 2,
    educationQualification: "B.A. Political Science, University of Rajasthan",
    websiteUrl: null,
    termStart: "2024-06-10",
    termEnd: "2029-06-09",
    profilePhoto: null,
    createdAt: "2024-06-10T10:00:00.000Z",
  },
  {
    id: "2",
    name: "Priya Deshmukh",
    role: "POLITICIAN",
    level: "NATIONAL",
    party: "Indian National Congress",
    department: "Parliamentary Standing Committee on Education",
    position: "Member of Parliament (Lok Sabha)",
    constituency: "Pune",
    constituencyType: "Lok Sabha",
    state: "Maharashtra",
    district: "Pune",
    assets: 28000000,
    criminalCases: 0,
    educationQualification: "M.A. Education Policy, TISS Mumbai",
    websiteUrl: null,
    termStart: "2024-06-10",
    termEnd: "2029-06-09",
    profilePhoto: null,
    createdAt: "2024-06-10T10:00:00.000Z",
  },
  {
    id: "4",
    name: "Arjun Singh Mehta",
    role: "POLITICIAN",
    level: "NATIONAL",
    party: "Bharatiya Janata Party",
    department: "Ministry of Home Affairs",
    position: "Cabinet Minister",
    constituency: "Varanasi Cantonment",
    constituencyType: "Lok Sabha",
    state: "Uttar Pradesh",
    district: "Varanasi",
    assets: 120000000,
    criminalCases: 4,
    educationQualification: "LL.B., Banaras Hindu University",
    websiteUrl: null,
    termStart: "2019-05-30",
    termEnd: "2024-05-29",
    profilePhoto: null,
    createdAt: "2019-05-30T10:00:00.000Z",
  },
  {
    id: "5",
    name: "Kavitha Reddy",
    role: "POLITICIAN",
    level: "NATIONAL",
    party: "Bharat Rashtra Samithi",
    department: "Parliamentary Standing Committee on Finance",
    position: "Member of Parliament (Rajya Sabha)",
    constituency: "Telangana",
    constituencyType: "Rajya Sabha",
    state: "Telangana",
    district: "Hyderabad",
    assets: 350000000,
    criminalCases: 1,
    educationQualification: "M.B.A., Osmania University",
    websiteUrl: null,
    termStart: "2022-06-21",
    termEnd: "2028-06-20",
    profilePhoto: null,
    createdAt: "2022-06-21T10:00:00.000Z",
  },
  // ===================== STATE LEVEL =====================
  {
    id: "6",
    name: "Suresh Nair",
    role: "POLITICIAN",
    level: "STATE",
    party: "Indian National Congress",
    department: "Chief Minister's Office, Kerala",
    position: "Chief Minister",
    constituency: "Thrissur",
    constituencyType: "Vidhan Sabha",
    state: "Kerala",
    district: "Thrissur",
    assets: 55000000,
    criminalCases: 0,
    educationQualification: "M.Sc. Physics, University of Kerala",
    websiteUrl: null,
    termStart: "2021-05-20",
    termEnd: "2026-05-19",
    profilePhoto: null,
    createdAt: "2021-05-20T10:00:00.000Z",
  },
  {
    id: "7",
    name: "Fatima Ahmed",
    role: "POLITICIAN",
    level: "STATE",
    party: "All India Trinamool Congress",
    department: "Women and Child Development, West Bengal",
    position: "MLA & State Minister",
    constituency: "Park Circus",
    constituencyType: "Vidhan Sabha",
    state: "West Bengal",
    district: "Kolkata",
    assets: 18000000,
    criminalCases: 0,
    educationQualification: "B.A. Social Work, Presidency University",
    websiteUrl: null,
    termStart: "2021-05-05",
    termEnd: "2026-05-04",
    profilePhoto: null,
    createdAt: "2021-05-05T10:00:00.000Z",
  },
  {
    id: "8",
    name: "Devendra Patil",
    role: "POLITICIAN",
    level: "STATE",
    party: "Nationalist Congress Party (SP)",
    department: "Public Works Department, Maharashtra",
    position: "State Minister (PWD) & MLA",
    constituency: "Sangli",
    constituencyType: "Vidhan Sabha",
    state: "Maharashtra",
    district: "Sangli",
    assets: 85000000,
    criminalCases: 3,
    educationQualification: "B.E. Civil, Shivaji University Kolhapur",
    websiteUrl: null,
    termStart: "2024-01-05",
    termEnd: "2029-01-04",
    profilePhoto: null,
    createdAt: "2024-01-05T10:00:00.000Z",
  },
  {
    id: "9",
    name: "Harpreet Kaur Bhatia",
    role: "POLITICIAN",
    level: "STATE",
    party: "Aam Aadmi Party",
    department: "Health & Education, Punjab",
    position: "MLA",
    constituency: "Amritsar North",
    constituencyType: "Vidhan Sabha",
    state: "Punjab",
    district: "Amritsar",
    assets: 12000000,
    criminalCases: 0,
    educationQualification: "M.D. (Medicine), AIIMS Delhi",
    websiteUrl: null,
    termStart: "2022-03-16",
    termEnd: "2027-03-15",
    profilePhoto: null,
    createdAt: "2022-03-16T10:00:00.000Z",
  },
  // ===================== DISTRICT LEVEL =====================
  {
    id: "3",
    name: "Vikram Singh Chauhan",
    role: "BUREAUCRAT",
    level: "DISTRICT",
    party: null,
    department: "District Administration, Lucknow",
    position: "District Collector (IAS)",
    constituency: null,
    constituencyType: null,
    state: "Uttar Pradesh",
    district: "Lucknow",
    assets: 9800000,
    criminalCases: 0,
    educationQualification: "IAS (2011 Batch) | M.Sc. Economics, JNU",
    websiteUrl: null,
    termStart: "2023-08-01",
    termEnd: null,
    profilePhoto: null,
    createdAt: "2023-08-01T10:00:00.000Z",
  },
  {
    id: "10",
    name: "Anand Krishnamurthy",
    role: "BUREAUCRAT",
    level: "DISTRICT",
    party: null,
    department: "District Collectorate, Chennai",
    position: "District Collector & DM (IAS)",
    constituency: null,
    constituencyType: null,
    state: "Tamil Nadu",
    district: "Chennai",
    assets: 8200000,
    criminalCases: 0,
    educationQualification: "IAS (2014 Batch) | B.Tech IIT Madras",
    websiteUrl: null,
    termStart: "2023-04-01",
    termEnd: null,
    profilePhoto: null,
    createdAt: "2023-04-01T10:00:00.000Z",
  },
  {
    id: "11",
    name: "Ravi Shankar Gupta",
    role: "POLITICIAN",
    level: "DISTRICT",
    party: "Bharatiya Janata Party",
    department: "Zila Parishad, Varanasi",
    position: "Zila Parishad President",
    constituency: "Varanasi Zila Panchayat Ward 12",
    constituencyType: "Zila Parishad",
    state: "Uttar Pradesh",
    district: "Varanasi",
    assets: 22000000,
    criminalCases: 1,
    educationQualification: "B.Com, Banaras Hindu University",
    websiteUrl: null,
    termStart: "2021-11-20",
    termEnd: "2026-11-19",
    profilePhoto: null,
    createdAt: "2021-11-20T10:00:00.000Z",
  },
  {
    id: "12",
    name: "Meena Tiwari",
    role: "POLITICIAN",
    level: "DISTRICT",
    party: "Janata Dal (United)",
    department: "Zila Parishad, Patna",
    position: "Zila Parishad Chairperson",
    constituency: "Patna Sadar Zila Ward 5",
    constituencyType: "Zila Parishad",
    state: "Bihar",
    district: "Patna",
    assets: 14000000,
    criminalCases: 0,
    educationQualification: "B.A. Political Science, Patna University",
    websiteUrl: null,
    termStart: "2021-12-15",
    termEnd: "2026-12-14",
    profilePhoto: null,
    createdAt: "2021-12-15T10:00:00.000Z",
  },
  // ===================== BLOCK LEVEL =====================
  {
    id: "13",
    name: "Ramesh Kumar Yadav",
    role: "POLITICIAN",
    level: "BLOCK",
    party: "Samajwadi Party",
    department: "Block Panchayat, Buxar",
    position: "Block Pramukh",
    constituency: "Buxar Block",
    constituencyType: "Block Panchayat",
    state: "Bihar",
    district: "Buxar",
    assets: 4500000,
    criminalCases: 0,
    educationQualification: "Higher Secondary, Bihar Board",
    websiteUrl: null,
    termStart: "2021-06-15",
    termEnd: "2026-06-14",
    profilePhoto: null,
    createdAt: "2021-06-15T10:00:00.000Z",
  },
  {
    id: "14",
    name: "Sunita Devi",
    role: "BUREAUCRAT",
    level: "BLOCK",
    party: null,
    department: "Block Development Office, Gorakhpur",
    position: "Block Development Officer",
    constituency: null,
    constituencyType: null,
    state: "Uttar Pradesh",
    district: "Gorakhpur",
    assets: 3800000,
    criminalCases: 0,
    educationQualification: "PCS (2018 Batch) | M.A. Economics, Lucknow University",
    websiteUrl: null,
    termStart: "2022-07-01",
    termEnd: null,
    profilePhoto: null,
    createdAt: "2022-07-01T10:00:00.000Z",
  },
  {
    id: "15",
    name: "Abdul Rahman Khan",
    role: "POLITICIAN",
    level: "BLOCK",
    party: "Indian National Congress",
    department: "Block Panchayat, Malappuram",
    position: "Block Panchayat President",
    constituency: "Tirur Block",
    constituencyType: "Block Panchayat",
    state: "Kerala",
    district: "Malappuram",
    assets: 5200000,
    criminalCases: 0,
    educationQualification: "B.A. Economics, Calicut University",
    websiteUrl: null,
    termStart: "2020-12-05",
    termEnd: "2025-12-04",
    profilePhoto: null,
    createdAt: "2020-12-05T10:00:00.000Z",
  },
  // ===================== PANCHAYAT LEVEL =====================
  {
    id: "16",
    name: "Munni Devi",
    role: "POLITICIAN",
    level: "PANCHAYAT",
    party: "Independent",
    department: "Gram Panchayat, Sitapur",
    position: "Gram Pradhan",
    constituency: "Sitapur Gram Panchayat",
    constituencyType: "Gram Panchayat",
    state: "Rajasthan",
    district: "Sikar",
    assets: 850000,
    criminalCases: 0,
    educationQualification: "Class 10, Rajasthan Board",
    websiteUrl: null,
    termStart: "2020-01-26",
    termEnd: "2025-01-25",
    profilePhoto: null,
    createdAt: "2020-01-26T10:00:00.000Z",
  },
  {
    id: "17",
    name: "Shambhu Lal Patel",
    role: "POLITICIAN",
    level: "PANCHAYAT",
    party: "Bharatiya Janata Party",
    department: "Gram Panchayat, Anand",
    position: "Sarpanch",
    constituency: "Karamsad Gram Panchayat",
    constituencyType: "Gram Panchayat",
    state: "Gujarat",
    district: "Anand",
    assets: 1200000,
    criminalCases: 0,
    educationQualification: "B.Com, Sardar Patel University",
    websiteUrl: null,
    termStart: "2021-03-20",
    termEnd: "2026-03-19",
    profilePhoto: null,
    createdAt: "2021-03-20T10:00:00.000Z",
  },
  {
    id: "18",
    name: "Krishnaswamy Rangan",
    role: "POLITICIAN",
    level: "PANCHAYAT",
    party: "Dravida Munnetra Kazhagam",
    department: "Village Panchayat, Madurai",
    position: "Ward Member",
    constituency: "Villapuram Panchayat Ward 3",
    constituencyType: "Gram Panchayat",
    state: "Tamil Nadu",
    district: "Madurai",
    assets: 620000,
    criminalCases: 0,
    educationQualification: "Diploma in Civil Engineering, Anna University",
    websiteUrl: null,
    termStart: "2022-02-19",
    termEnd: "2027-02-18",
    profilePhoto: null,
    createdAt: "2022-02-19T10:00:00.000Z",
  },
];

let promises = [
  // Official 1 — Rajesh Kumar Sharma
  {
    id: "1", officialId: "1",
    title: "Build 500km national highway connecting Jaipur to Udaipur (NH-148D)",
    description: "Promised during 2024 election campaign to complete a 4-lane highway by 2027. Contract awarded to NHAI contractor consortium.",
    budgetAllotted: 12000000000, budgetSpent: 3500000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2027-03-31",
    createdAt: "2024-06-15T10:00:00.000Z", updatedAt: "2025-03-01T10:00:00.000Z",
  },
  {
    id: "2", officialId: "1",
    title: "Install 200 EV charging stations along Rajasthan state highways",
    description: "MoU signed with EESL for green transport corridor as part of PM e-DRIVE scheme.",
    budgetAllotted: 800000000, budgetSpent: 0,
    status: "NOT_STARTED", proofImages: [], sourceUrl: null,
    deadline: "2026-12-31",
    createdAt: "2024-08-01T10:00:00.000Z", updatedAt: "2024-08-01T10:00:00.000Z",
  },
  // Official 2 — Priya Deshmukh
  {
    id: "3", officialId: "2",
    title: "Open 50 new government model schools in rural Maharashtra",
    description: "Committed to building PM SHRI schools in underserved talukas by 2026.",
    budgetAllotted: 500000000, budgetSpent: 0,
    status: "NOT_STARTED", proofImages: [], sourceUrl: null,
    deadline: "2026-03-31",
    createdAt: "2024-06-20T10:00:00.000Z", updatedAt: "2024-06-20T10:00:00.000Z",
  },
  {
    id: "4", officialId: "2",
    title: "Secure ₹200Cr central funding for Pune startup incubation centres",
    description: "Lobby for Startup India extension to Tier-2 cities in Maharashtra.",
    budgetAllotted: 200000000, budgetSpent: 45000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-09-30",
    createdAt: "2024-07-01T10:00:00.000Z", updatedAt: "2025-01-15T10:00:00.000Z",
  },
  // Official 3 — Vikram Singh Chauhan
  {
    id: "5", officialId: "3",
    title: "Fix drainage system in old Lucknow (Phase 1 — 12 wards)",
    description: "Approved plan to overhaul sewage and drainage infrastructure in the old city area under Smart Cities Mission.",
    budgetAllotted: 800000000, budgetSpent: 200000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2026-09-30",
    createdAt: "2023-09-01T10:00:00.000Z", updatedAt: "2024-12-01T10:00:00.000Z",
  },
  {
    id: "6", officialId: "3",
    title: "Digitisation of all land records in Lucknow district",
    description: "Swamitva scheme + DILRMP implementation across all 845 villages in the district.",
    budgetAllotted: 120000000, budgetSpent: 95000000,
    status: "COMPLETED", proofImages: [], sourceUrl: null,
    deadline: "2024-12-31",
    createdAt: "2023-10-01T10:00:00.000Z", updatedAt: "2025-01-05T10:00:00.000Z",
  },
  // Official 4 — Arjun Singh Mehta
  {
    id: "7", officialId: "4",
    title: "Deploy 25,000 additional CAPF personnel to conflict-affected districts",
    description: "Announced in Parliament during Winter Session 2023. Personnel deployment in LWE-affected districts.",
    budgetAllotted: 9000000000, budgetSpent: 9000000000,
    status: "COMPLETED", proofImages: [], sourceUrl: null,
    deadline: "2024-06-30",
    createdAt: "2023-12-20T10:00:00.000Z", updatedAt: "2024-07-10T10:00:00.000Z",
  },
  {
    id: "8", officialId: "4",
    title: "Implement National Automated Facial Recognition System (AFRS) in 30 cities",
    description: "National surveillance modernisation. Privacy concerns raised by civil society groups.",
    budgetAllotted: 15000000000, budgetSpent: 4500000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2027-03-31",
    createdAt: "2022-01-15T10:00:00.000Z", updatedAt: "2025-02-01T10:00:00.000Z",
  },
  // Official 5 — Kavitha Reddy
  {
    id: "9", officialId: "5",
    title: "Secure ₹1 lakh crore special category status package for Telangana",
    description: "Raised in Rajya Sabha multiple times. Central government has denied special category status.",
    budgetAllotted: null, budgetSpent: null,
    status: "FAILED", proofImages: [], sourceUrl: null,
    deadline: "2024-06-01",
    createdAt: "2022-07-01T10:00:00.000Z", updatedAt: "2024-06-15T10:00:00.000Z",
  },
  // Official 6 — Suresh Nair
  {
    id: "10", officialId: "6",
    title: "Complete Kerala Fiber Optic Network (K-FON) rollout to 20 lakh households",
    description: "Free internet to BPL families and subsidised broadband for APL households across Kerala.",
    budgetAllotted: 15000000000, budgetSpent: 13200000000,
    status: "COMPLETED", proofImages: [], sourceUrl: null,
    deadline: "2024-03-31",
    createdAt: "2022-05-20T10:00:00.000Z", updatedAt: "2024-04-10T10:00:00.000Z",
  },
  {
    id: "11", officialId: "6",
    title: "Establish 1000 MW solar power capacity in Kerala by 2025",
    description: "KSEB Solar Energy Policy 2022 implementation. Rooftop + utility scale.",
    budgetAllotted: 60000000000, budgetSpent: 22000000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-12-31",
    createdAt: "2022-06-01T10:00:00.000Z", updatedAt: "2025-03-15T10:00:00.000Z",
  },
  // Official 7 — Fatima Ahmed
  {
    id: "12", officialId: "7",
    title: "Build 5 women's shelter homes across Kolkata with 1000-bed capacity",
    description: "Part of state Banglar Bari scheme for homeless women and trafficking survivors.",
    budgetAllotted: 350000000, budgetSpent: 310000000,
    status: "COMPLETED", proofImages: [], sourceUrl: null,
    deadline: "2024-09-30",
    createdAt: "2021-06-01T10:00:00.000Z", updatedAt: "2024-10-05T10:00:00.000Z",
  },
  // Official 8 — Devendra Patil
  {
    id: "13", officialId: "8",
    title: "Repair 1200km of state highways in Sangli-Kolhapur belt",
    description: "Promised within 18 months of taking charge. Survey complete, tenders awarded.",
    budgetAllotted: 4500000000, budgetSpent: 900000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2026-06-30",
    createdAt: "2024-02-01T10:00:00.000Z", updatedAt: "2025-01-10T10:00:00.000Z",
  },
  // Official 9 — Harpreet Kaur
  {
    id: "14", officialId: "9",
    title: "Open Aam Aadmi Clinics in all 117 Vidhan Sabha constituencies in Punjab",
    description: "Mohalla Clinic model replicated in Punjab. 72 clinics operational as on Apr 2025.",
    budgetAllotted: 3500000000, budgetSpent: 2100000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-09-30",
    createdAt: "2022-04-01T10:00:00.000Z", updatedAt: "2025-04-01T10:00:00.000Z",
  },
  {
    id: "15", officialId: "9",
    title: "Free electricity up to 300 units per month for all Punjab households",
    description: "AAP election promise implemented from July 2022. Ongoing subsidy.",
    budgetAllotted: 18000000000, budgetSpent: 12400000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: null,
    createdAt: "2022-07-01T10:00:00.000Z", updatedAt: "2025-02-01T10:00:00.000Z",
  },
  // Official 11 — Ravi Shankar Gupta
  {
    id: "16", officialId: "11",
    title: "Construct 15 community halls across Varanasi district panchayats",
    description: "14th Finance Commission devolution funds utilised for construction.",
    budgetAllotted: 75000000, budgetSpent: 68000000,
    status: "COMPLETED", proofImages: [], sourceUrl: null,
    deadline: "2024-06-30",
    createdAt: "2022-01-15T10:00:00.000Z", updatedAt: "2024-07-20T10:00:00.000Z",
  },
  // Official 13 — Ramesh Kumar Yadav
  {
    id: "17", officialId: "13",
    title: "Install hand pump and Jal Jeevan Mission pipelines in 45 villages",
    description: "Promised 100% potable water coverage in Buxar block by 2024.",
    budgetAllotted: 45000000, budgetSpent: 30000000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-06-30",
    createdAt: "2021-07-01T10:00:00.000Z", updatedAt: "2024-11-01T10:00:00.000Z",
  },
  // Official 15 — Abdul Rahman Khan
  {
    id: "18", officialId: "15",
    title: "Build anganwadi centres and library in each panchayat of Tirur block",
    description: "12 anganwadis operational; library project pending land acquisition.",
    budgetAllotted: 8500000, budgetSpent: 5100000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-03-31",
    createdAt: "2021-02-01T10:00:00.000Z", updatedAt: "2024-10-15T10:00:00.000Z",
  },
  // Official 16 — Munni Devi
  {
    id: "19", officialId: "16",
    title: "Complete PM Awas Yojana homes for 85 BPL families in Sitapur",
    description: "62 homes constructed; 23 pending due to land disputes.",
    budgetAllotted: 12750000, budgetSpent: 9300000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2024-12-31",
    createdAt: "2020-04-01T10:00:00.000Z", updatedAt: "2024-12-01T10:00:00.000Z",
  },
  // Official 17 — Shambhu Patel
  {
    id: "20", officialId: "17",
    title: "Concrete roads connecting all 6 hamlets of Karamsad Panchayat",
    description: "4 roads completed under PMGSY. 2 pending monsoon-season work.",
    budgetAllotted: 4200000, budgetSpent: 3600000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-07-31",
    createdAt: "2021-05-01T10:00:00.000Z", updatedAt: "2025-01-20T10:00:00.000Z",
  },
  // Official 18 — Krishnaswamy Rangan
  {
    id: "21", officialId: "18",
    title: "LED streetlights in all lanes of Ward 3, Villapuram Panchayat",
    description: "56 streetlights installed; 8 lanes still pending civic approval.",
    budgetAllotted: 850000, budgetSpent: 640000,
    status: "IN_PROGRESS", proofImages: [], sourceUrl: null,
    deadline: "2025-05-31",
    createdAt: "2022-04-01T10:00:00.000Z", updatedAt: "2025-03-10T10:00:00.000Z",
  },
];

let allegations = [
  {
    id: "1", officialId: "1",
    title: "Inflated per-km cost on NH-148D — 40% above comparable projects",
    description: "CAG preliminary report suggests per-km cost is ₹24 crore vs national average of ₹17 crore. Contracts awarded to a single consortium without competitive open bidding under emergency provisions.",
    severity: "HIGH", status: "INVESTIGATING",
    proofImages: [], sourceUrl: null,
    createdAt: "2025-01-15T10:00:00.000Z", updatedAt: "2025-03-20T10:00:00.000Z",
  },
  {
    id: "2", officialId: "1",
    title: "EV charging station tender awarded to relative's company",
    description: "RTI reveals the primary vendor for EV charging stations shares a directorship with the minister's brother-in-law. Value: ₹22 crore.",
    severity: "MEDIUM", status: "UNVERIFIED",
    proofImages: [], sourceUrl: null,
    createdAt: "2025-02-10T10:00:00.000Z", updatedAt: "2025-02-10T10:00:00.000Z",
  },
  {
    id: "3", officialId: "3",
    title: "Ghost workers on Lucknow drainage project payroll",
    description: "Whistleblower claims 30% of listed workers do not exist and their wages are being siphoned through bogus bank accounts. Vigilance inquiry ordered by DG.",
    severity: "MEDIUM", status: "INVESTIGATING",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-09-20T10:00:00.000Z", updatedAt: "2025-01-10T10:00:00.000Z",
  },
  {
    id: "4", officialId: "4",
    title: "AFRS surveillance system awarded without competitive bidding",
    description: "Parliamentary standing committee note leaked showing MHA bypassed standard procurement for ₹1,500 crore AFRS contract citing national security exemptions.",
    severity: "HIGH", status: "INVESTIGATING",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-08-01T10:00:00.000Z", updatedAt: "2025-02-15T10:00:00.000Z",
  },
  {
    id: "5", officialId: "4",
    title: "Money laundering allegations linked to Varanasi real estate",
    description: "ED investigation (ECIR no. not disclosed) reportedly examines ₹80 crore in property purchases in minister's name and family trust between 2020-2024.",
    severity: "HIGH", status: "INVESTIGATING",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-11-20T10:00:00.000Z", updatedAt: "2025-04-05T10:00:00.000Z",
  },
  {
    id: "6", officialId: "5",
    title: "Hyderabad liquor policy scam — linked party funding allegations",
    description: "Delhi liquor scam chargesheet mentions BRS functionaries. ED claims proceeds routed through Kavitha Reddy's media group. MP denies all charges.",
    severity: "HIGH", status: "INVESTIGATING",
    proofImages: [], sourceUrl: null,
    createdAt: "2023-03-10T10:00:00.000Z", updatedAt: "2024-12-01T10:00:00.000Z",
  },
  {
    id: "7", officialId: "6",
    title: "KIIFB borrowing opacity — ₹60,000 crore off-budget debt concerns",
    description: "CAG Kerala report says KIIFB borrowings don't appear on state budget, creating contingent liability. Opposition alleges data suppression before elections.",
    severity: "MEDIUM", status: "UNVERIFIED",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-12-15T10:00:00.000Z", updatedAt: "2024-12-15T10:00:00.000Z",
  },
  {
    id: "8", officialId: "8",
    title: "PWD road repair tenders manipulated in Sangli — CBI complaint filed",
    description: "Contractor association has filed a CBI complaint alleging that tenders were pre-decided and valid bids rejected. Total amount: ₹320 crore.",
    severity: "HIGH", status: "UNVERIFIED",
    proofImages: [], sourceUrl: null,
    createdAt: "2025-01-20T10:00:00.000Z", updatedAt: "2025-01-20T10:00:00.000Z",
  },
  {
    id: "9", officialId: "11",
    title: "Community hall construction funds partly diverted — RTI revealed",
    description: "RTI response shows 3 of 15 community halls have quality defects and measurements don't match completion certificates. Estimated diversion: ₹35 lakh.",
    severity: "LOW", status: "UNVERIFIED",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-10-05T10:00:00.000Z", updatedAt: "2024-10-05T10:00:00.000Z",
  },
  {
    id: "10", officialId: "2",
    title: "Startup funding allocation bypassed prescribed committee norms",
    description: "Internal INC report says MP applied for central funds through out-of-turn process benefitting a Pune-based firm linked to donor.",
    severity: "LOW", status: "DISMISSED",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-07-10T10:00:00.000Z", updatedAt: "2024-09-01T10:00:00.000Z",
  },
  {
    id: "11", officialId: "13",
    title: "Jal Jeevan Mission pipes procured at inflated price from single vendor",
    description: "Block Development Committee records show pipes procured at ₹580/metre vs market rate of ₹320/metre. Difference: ₹78 lakh. Block Pramukh denies involvement.",
    severity: "MEDIUM", status: "UNVERIFIED",
    proofImages: [], sourceUrl: null,
    createdAt: "2024-08-15T10:00:00.000Z", updatedAt: "2024-08-15T10:00:00.000Z",
  },
];

let claims = [
  {
    id: "1", officialId: "2",
    submittedBy: "citizen_satara_99",
    type: "PROMISE_UPDATE",
    title: "No school construction started in Satara — 2 years since announcement",
    description: "I live in Satara district. No land has been acquired and no construction has begun for the promised PM SHRI schools. No response to RTI application filed in January 2025.",
    evidence: [], status: "PENDING",
    aiVerificationNote: null, aiConfidence: null,
    linkedPromiseId: "3", linkedAllegationId: null,
    createdAt: "2025-03-01T12:00:00.000Z", verifiedAt: null,
  },
  {
    id: "2", officialId: "1",
    submittedBy: "jaipur_techie_anon",
    type: "ALLEGATION",
    title: "NH-148D contractor subcontracted 60% of work without NHAI approval",
    description: "I work in the construction sector. The main contractor has further subcontracted to 3 firms without NHAI clearance, violating tender norms. I have WhatsApp evidence of cash transactions.",
    evidence: [], status: "VERIFIED",
    aiVerificationNote: "🤖 AI Analysis (72% confidence): Claim references construction sub-contracting violations — appears factually grounded. Supporting evidence mentioned. Manual verification confirmed by volunteer network.",
    aiConfidence: 72,
    linkedPromiseId: "1", linkedAllegationId: "1",
    createdAt: "2025-02-10T14:00:00.000Z", verifiedAt: "2025-02-28T10:00:00.000Z",
  },
  {
    id: "3", officialId: "4",
    submittedBy: "rights_researcher_delhi",
    type: "ALLEGATION",
    title: "AFRS deployed in Varanasi without mandatory privacy impact assessment",
    description: "Filed RTI in Dec 2024. MHA response shows no Privacy Impact Assessment was conducted before deploying AFRS cameras in 18 Varanasi locations. This violates Puttaswamy judgment safeguards.",
    evidence: [], status: "PENDING",
    aiVerificationNote: null, aiConfidence: null,
    linkedPromiseId: null, linkedAllegationId: "4",
    createdAt: "2025-01-15T09:00:00.000Z", verifiedAt: null,
  },
  {
    id: "4", officialId: "9",
    submittedBy: "punjab_farmer_anon",
    type: "PROMISE_UPDATE",
    title: "Aam Aadmi Clinic in Tarn Taran non-functional for 3 months",
    description: "The AAC in our village has been closed since January due to doctor shortage. MLA has not visited or addressed this.",
    evidence: [], status: "PENDING",
    aiVerificationNote: null, aiConfidence: null,
    linkedPromiseId: "14", linkedAllegationId: null,
    createdAt: "2025-04-01T11:00:00.000Z", verifiedAt: null,
  },
  {
    id: "5", officialId: "13",
    submittedBy: "buxar_ngo_volunteer",
    type: "ALLEGATION",
    title: "Water pipes installed are sub-standard — leaking within 6 months",
    description: "Of the 45 villages promised water pipelines, 14 have reported leakages within 6 months of installation. Pipes appear to be thinner-walled than CPWD specifications. Photos available.",
    evidence: [], status: "PENDING",
    aiVerificationNote: null, aiConfidence: null,
    linkedPromiseId: "17", linkedAllegationId: "11",
    createdAt: "2025-03-20T15:00:00.000Z", verifiedAt: null,
  },
];

const db = { officials, promises, allegations, claims };
export default db;
